### ISSUE TITLE
how can i show vote icon with php code?

### ISSUE THREAD

**Issue by mo3t4f4** [norcross/quick-vote#1]
hi
i using the quick vote plugin.WP 
i don't want checked Display the voting buttons on single posts or single pages.
I need php code for query template.
i want show vote icon with php code.

please help me.

**Comment by norcross** [comment]
this hasn't been updated in over two years and I don't plan on adding any new functionality at this time. if you want to fork / modify it, please feel free. you'd wanna disable the_content filters and re-run the code with a template tag.

**Comment by mo3t4f4** [comment]
oh, ok, i understand now. the_content
thank you
